---
- name: activity4 install apache and php on both nodes
  become: yes  
  hosts: webservers
  tasks:
    - name: install apache and php
      ansible.builtin.apt:
        name: 
          - apache2
          - php 
          - libapache2-mod-php 
          - php-mysql
        state: present
        update_cache: yes 
      when: ansible_facts["os_family"] == "Debian"
    - name: insatll apache
      ansible.builtin.dnf:
        name:
          - httpd
          - php 
          - php-cli 
          - php-common 
        state: present 
      when: ansible_facts["os_family"] == "RedHat"  
    - name: create info.php
      ansible.builtin.copy:
        content: '<?php phpinfo(); ?>'
        dest: /var/www/html/info.phpx  
    - name: enssure httpd service is runnimg
      ansible.builtin.service:
        name: httpd
        enabled: yes  
        state : started    
      when: ansible_facts["os_family"] == "RedHat"    
 

      