---
- name: activity 3 install apache2 and php-mysql 
  become: yes  
  hosts: all
  tasks:
    - name: insatll apache
      ansible.builtin.dnf:
        name:
          - httpd
          - php 
          - php-cli 
          - php-common 
        state: present
    - name: create info.php
      ansible.builtin.copy:
        content: '<?php phpinfo(); ?>'
        dest: /var/www/html/info.phpx

                
          
  